name: Altars
version: '${project.version}'
main: net.candorservices.lisacek.altars.Altars
authors: [ LISACEK ]
depend:
  - MythicMobs
  - PlaceholderAPI
commands:
  altars:
    description: Altars command